services:
  backend_service:
    build: .
    command:
      uv run gunicorn root.wsgi:application --bind 0.0.0.0:8000
#    ports:
#      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - postgres_service
      - redis_service
    restart: on-failure

  celery_service:
    build: .
    command: >
      uv run celery -A root worker -l INFO
    env_file:
      - .env.prod
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - postgres_service
      - redis_service

  celery_flower_service:
    build: .
    command: >
      uv run celery -A root.celery flower --port=5001
    env_file:
      - .env.prod
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "5001:5001"
    depends_on:
      - postgres_service
      - redis_service
      - celery_service

  celery_beat_service:
    build: .
    command: >
      uv run celery -A root beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.prod
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - postgres_service
      - redis_service

  postgres_service:
    image: postgres:alpine
    env_file: .env.prod
#    ports:
#      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis_service:
    image: redis:alpine
#    ports:
#      - "6379:6379"

  nginx_service:
    image: nginx:alpine
    ports:
      - "8005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - backend_service
      - redis_service
      - postgres_service
      - celery_service
    restart: always

volumes:
  pg_data:
  backend_static:
  backend_media:
