services:
  backend_service:
    build: .
    command: >
      uv run gunicorn root.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - postgres_service
      - redis_service

  postgres_service:
    image: postgres:alpine
    env_file: .env.prod
#    ports:
#      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis_service:
    image: redis:alpine
#    ports:
#      - "6379:6379"

volumes:
  pg_data:
  backend_static:
  backend_media:
