# Generated by Django 6.0 on 2026-01-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
