# Generated by Django 6.0 on 2026-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("manager", "Manager")],
                default="user",
                max_length=25,
            ),
        ),
    ]
