# Generated by Django 6.0 on 2026-01-22 10:45

import apps.models.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.models.managers.CustomUserManager()),
            ],
        ),
    ]
