# Generated by Django 6.0 on 2026-02-03 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_product_seller"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "product")},
        ),
    ]
